#pragma once

#ifndef CONSTANTS_CUH
#define CONSTANTS_CUH

#define WARPSIZE 32
#define MAXTHREADSPERBLOCK 1024
#define MAXBLOCKS 65535
#define PARTITION_SIZE 256
#define MIN_VALUE 0
#define MAX_VALUE 65535

#endif
